mod id;
mod registry;

use std::path::PathBuf;

pub use id::*;
pub use registry::{CommandMeta, CommandRegistry};

/// UI-independent command payload dispatched by keyboard and mouse paths.
#[derive(Debug, Clone)]
pub enum Command {
    Invoke(String),
    InsertText(String),
    InsertNewline,
    DeleteBackward,
    DeleteWordBackward,
    DeleteWordForward,
    IndentSelection,
    OutdentSelection,
    ToggleLineComment,
    MoveLeft {
        extend: bool,
    },
    MoveRight {
        extend: bool,
    },
    MoveWordLeft {
        extend: bool,
    },
    MoveWordRight {
        extend: bool,
    },
    MoveUp {
        extend: bool,
    },
    MoveDown {
        extend: bool,
    },
    OpenFile(PathBuf),
    SelectTree(usize),
    ClickTree(usize),
    ToggleTree(usize),
    BeginSidebarResize,
    ResizeSidebar(u16),
    EndSidebarResize,
    SelectGit(usize),
    SelectGitAndOpen(usize),
    StageGit(usize),
    UnstageGit(usize),
    OpenGitDiff,
    SelectGitHunk(usize),
    GitHunkPrevious,
    GitHunkNext,
    GitHunkStageToggle,
    GitHunkRestore,
    GitHunkOpenFile,
    EditorScroll(i32),
    WorkspaceSearchInput(char),
    WorkspaceSearchBackspace,
    WorkspaceSearchSelect(usize),
    WorkspaceSearchSelectAndOpen(usize),
    WorkspaceSearchOpen,
    WorkspaceSearchToggleCase,
    WorkspaceSearchToggleWord,
    WorkspaceSearchToggleRegex,
    WorkspaceSearchToggleHidden,
    WorkspaceSearchToggleBinary,
    WorkspaceSearchToggleFile(PathBuf),
    TerminalInput(Vec<u8>),
    TerminalPaste(String),
    TerminalScroll(i32),
    FocusTerminal,
    FocusSidebar,
    TerminalSetSelection {
        row: usize,
        column: usize,
        extend: bool,
    },
    TerminalCopy,
    TerminalOpenReference {
        row: usize,
        column: Option<usize>,
    },
    TerminalSearchNext,
    TerminalSearchPrevious,
    DiagnosticSelect(usize),
    DiagnosticOpen,
    DiagnosticCycleFilter,
    DiagnosticCycleSource,
    DiagnosticToggleCurrentFile,
    LspLocationSelect(usize),
    LspLocationOpen,
    LspCodeActionSelect(usize),
    LspCodeActionApply,
    SelectTab(usize),
    BeginTabDrag(usize),
    ReorderTab {
        from: usize,
        to: usize,
    },
    TogglePinTab(usize),
    EndTabDrag,
    SplitEditor,
    FocusNextEditorGroup,
    FocusEditorGroup(bool),
    CloseEditorSplit,
    CloseTab(usize),
    SetCursor {
        char_offset: usize,
        extend: bool,
    },
    SearchNext,
    SearchPrevious,
    SearchToggleReplaceField,
    ReplaceNext,
    ReplaceAll,
    RecoveryRecover,
    RecoveryDiscard,
    RecoveryLater,
    PaletteInput(char),
    PaletteBackspace,
    PaletteNewline,
    PaletteAccept,
    Cancel,
    Resize(u16, u16),
}
